const SEARCH_STATUS = {
    IDLE: 'IDLE',
    SEARCHING: 'SEARCHING',
    SUCCESS: 'SUCCESS',
};


const UPLOAD_STATUS = {
    EMPTY: 'EMPTY',
    UPLOADING: 'UPLOADING',
    UPLOADED: 'UPLOADED',
    SUBMITTING: 'SUBMITTING',
    SUBMITTED: 'SUBMITTED',
};


export {
    SEARCH_STATUS,
    UPLOAD_STATUS,
}